version: '3.7'
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy


  frontend:
    build: ./frontend
    ports:
      - "3000:3000"

  pinger:
    build: ./pinger
    depends_on:
      - backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pinger
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "pinger"]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
